defmodule Firmboot.AgdaFixtures do
  @moduledoc false
  alias Firmboot.{Model, Update}

  # Observe the real Elixir transition model. Only encode its returned values;
  # do not recompute the detector or migration here. Agda reduces its independent
  # model against these concrete values. This is finite agreement evidence.
  def write!(path) do
    cases =
      for schedule <- [:forward, :return], bits <- 0..31 do
        values = Integer.digits(bits, 2)
        values = List.duplicate(0, 5 - length(values)) ++ values
        requests = %{3 => [%Update{id: :forward, target: :v2, prepare_ticks: 0}]}

        requests =
          if schedule == :return,
            do: Map.put(requests, 4, [%Update{id: :return, target: :v1, prepare_ticks: 0}]),
            else: requests

        model = Model.run(values, requests, history_capacity: 32)
        activations = Enum.count(model.audit, &(&1.kind == :activated))
        expected_activations = if schedule == :return, do: 2, else: 1

        unless activations == expected_activations do
          raise "fixture did not reach the intended activation schedule"
        end

        inputs =
          values
          |> Enum.with_index(1)
          |> Enum.map(fn {value, seq} ->
            action =
              case {seq, schedule} do
                {3, _} -> "(switchNow v2)"
                {4, :return} -> "(switchNow v1)"
                _ -> "wait"
              end

            "(input #{bool(value)} #{action})"
          end)

        name = "#{schedule}#{bits}"

        """
        #{name} : current (service (run initialController #{list(inputs)})) ≡
          #{boundary(model)}
        #{name} = refl
        """
      end

    header = """
    {-# OPTIONS --safe --without-K #-}
    module Firmboot.ElixirAgreement where

    -- Generated by fixtures.exs from 64 actual Firmboot.Model.run executions.
    -- Exhaustive binary inputs of length five, under two fixed schedules.
    -- Includes normalized detector, retained history, frames and event journal.
    -- Excludes timing, pending/audit state, process behavior and generation tags.
    open import Firmboot.Prelude
    open import Firmboot.Detector
    open import Firmboot.Admission
    open import Firmboot.Lifecycle

    """

    File.write!(path, header <> Enum.join(cases, "\n"))
    IO.puts("Generated #{length(cases)} concrete Elixir agreement witnesses: #{path}")
  end

  defp bool(0), do: "false"
  defp bool(1), do: "true"
  defp bool(false), do: "false"
  defp bool(true), do: "true"

  defp list([]), do: "[]"
  defp list(items), do: "(" <> Enum.join(items, " ∷ ") <> " ∷ [])"

  defp episode(nil), do: "nothing"
  defp episode(e), do: "(just (episode #{e.first} #{bool(e.reported)}))"

  defp representation(%{version: :v1, detector: d}) do
    ongoing = if d.first, do: %{first: d.first, reported: d.sent}, else: nil
    "(V1 (cursor #{d.position} #{episode(ongoing)}) #{d.count})"
  end

  defp representation(%{version: :v2, detector: d}) do
    "(V2 (cursor #{d.position} #{episode(d.episode)}) #{list(Enum.map(d.window, &bool/1))})"
  end

  defp boundary(model) do
    history = list(Enum.map(model.history, &bool(&1.value)))

    frames =
      list(Enum.map(model.frames, &"(frame #{&1.seq} #{bool(&1.value)} #{&1.version})"))

    events =
      list(Enum.map(model.events, &"(event #{&1.episode} #{&1.detected_at} #{&1.version})"))

    "boundary #{representation(model)} #{history} #{frames} #{events}"
  end
end

case System.argv() do
  [path] -> Firmboot.AgdaFixtures.write!(path)
  _ -> raise "usage: mix run proofs/agda/fixtures.exs OUTPUT.agda"
end
