{-# OPTIONS --safe --without-K #-}
module Firmboot.ElixirAgreement where

-- Generated by fixtures.exs from 64 actual Firmboot.Model.run executions.
-- Exhaustive binary inputs of length five, under two fixed schedules.
-- Includes normalized detector, retained history, frames and event journal.
-- Excludes timing, pending/audit state, process behavior and generation tags.
open import Firmboot.Prelude
open import Firmboot.Detector
open import Firmboot.Admission
open import Firmboot.Lifecycle

forward0 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ false ∷ false ∷ [])) (false ∷ false ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward0 = refl

forward1 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (false ∷ false ∷ true ∷ [])) (false ∷ false ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward1 = refl

forward2 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ true ∷ false ∷ [])) (false ∷ false ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward2 = refl

forward3 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 4 false))) (false ∷ true ∷ true ∷ [])) (false ∷ false ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward3 = refl

forward4 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ false ∷ false ∷ [])) (false ∷ false ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward4 = refl

forward5 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (true ∷ false ∷ true ∷ [])) (false ∷ false ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward5 = refl

forward6 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ true ∷ false ∷ [])) (false ∷ false ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
forward6 = refl

forward7 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 3 true))) (true ∷ true ∷ true ∷ [])) (false ∷ false ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) ((event 3 5 v2) ∷ [])
forward7 = refl

forward8 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ false ∷ false ∷ [])) (false ∷ true ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
forward8 = refl

forward9 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (false ∷ false ∷ true ∷ [])) (false ∷ true ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
forward9 = refl

forward10 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ true ∷ false ∷ [])) (false ∷ true ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
forward10 = refl

forward11 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 4 false))) (false ∷ true ∷ true ∷ [])) (false ∷ true ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
forward11 = refl

forward12 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ false ∷ false ∷ [])) (false ∷ true ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
forward12 = refl

forward13 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (true ∷ false ∷ true ∷ [])) (false ∷ true ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
forward13 = refl

forward14 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ true ∷ false ∷ [])) (false ∷ true ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
forward14 = refl

forward15 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 2 true))) (true ∷ true ∷ true ∷ [])) (false ∷ true ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
forward15 = refl

forward16 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ false ∷ false ∷ [])) (true ∷ false ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward16 = refl

forward17 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (false ∷ false ∷ true ∷ [])) (true ∷ false ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward17 = refl

forward18 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ true ∷ false ∷ [])) (true ∷ false ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward18 = refl

forward19 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 4 false))) (false ∷ true ∷ true ∷ [])) (true ∷ false ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward19 = refl

forward20 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ false ∷ false ∷ [])) (true ∷ false ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward20 = refl

forward21 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (true ∷ false ∷ true ∷ [])) (true ∷ false ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward21 = refl

forward22 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ true ∷ false ∷ [])) (true ∷ false ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
forward22 = refl

forward23 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 3 true))) (true ∷ true ∷ true ∷ [])) (true ∷ false ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) ((event 3 5 v2) ∷ [])
forward23 = refl

forward24 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ false ∷ false ∷ [])) (true ∷ true ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward24 = refl

forward25 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (false ∷ false ∷ true ∷ [])) (true ∷ true ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward25 = refl

forward26 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (false ∷ true ∷ false ∷ [])) (true ∷ true ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward26 = refl

forward27 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 4 false))) (false ∷ true ∷ true ∷ [])) (true ∷ true ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward27 = refl

forward28 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ false ∷ false ∷ [])) (true ∷ true ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward28 = refl

forward29 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 5 false))) (true ∷ false ∷ true ∷ [])) (true ∷ true ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward29 = refl

forward30 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input false wait) ∷ []))) ≡
  boundary (V2 (cursor 5 nothing) (true ∷ true ∷ false ∷ [])) (true ∷ true ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward30 = refl

forward31 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true wait) ∷ (input true wait) ∷ []))) ≡
  boundary (V2 (cursor 5 (just (episode 1 true))) (true ∷ true ∷ true ∷ [])) (true ∷ true ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v2) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
forward31 = refl

return0 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ false ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
return0 = refl

return1 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (false ∷ false ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
return1 = refl

return2 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ false ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
return2 = refl

return3 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 4 true))) 2) (false ∷ false ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) ((event 4 5 v1) ∷ [])
return3 = refl

return4 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ false ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
return4 = refl

return5 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (false ∷ false ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
return5 = refl

return6 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ false ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) []
return6 = refl

return7 : current (service (run initialController ((input false wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 3 true))) 3) (false ∷ false ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 false v1) ∷ []) ((event 3 5 v1) ∷ [])
return7 = refl

return8 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ true ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
return8 = refl

return9 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (false ∷ true ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
return9 = refl

return10 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ true ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) []
return10 = refl

return11 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 4 true))) 2) (false ∷ true ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 4 5 v1) ∷ [])
return11 = refl

return12 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ true ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
return12 = refl

return13 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (false ∷ true ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
return13 = refl

return14 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (false ∷ true ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
return14 = refl

return15 : current (service (run initialController ((input false wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 2 true))) 4) (false ∷ true ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 false v1) ∷ []) ((event 2 3 v1) ∷ [])
return15 = refl

return16 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ false ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
return16 = refl

return17 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (true ∷ false ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
return17 = refl

return18 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ false ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
return18 = refl

return19 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 4 true))) 2) (true ∷ false ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) ((event 4 5 v1) ∷ [])
return19 = refl

return20 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ false ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
return20 = refl

return21 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (true ∷ false ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
return21 = refl

return22 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ false ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) []
return22 = refl

return23 : current (service (run initialController ((input true wait) ∷ (input false wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 3 true))) 3) (true ∷ false ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 false v1) ∷ (frame 1 true v1) ∷ []) ((event 3 5 v1) ∷ [])
return23 = refl

return24 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ true ∷ false ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return24 = refl

return25 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (true ∷ true ∷ false ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return25 = refl

return26 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ true ∷ false ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return26 = refl

return27 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input false (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 4 true))) 2) (true ∷ true ∷ false ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 false v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 4 5 v1) ∷ (event 1 2 v1) ∷ [])
return27 = refl

return28 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ true ∷ true ∷ false ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return28 = refl

return29 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input false (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 5 false))) 1) (true ∷ true ∷ true ∷ false ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 false v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return29 = refl

return30 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input false wait) ∷ []))) ≡
  boundary (V1 (cursor 5 nothing) 0) (true ∷ true ∷ true ∷ true ∷ false ∷ []) ((frame 5 false v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return30 = refl

return31 : current (service (run initialController ((input true wait) ∷ (input true wait) ∷ (input true (switchNow v2)) ∷ (input true (switchNow v1)) ∷ (input true wait) ∷ []))) ≡
  boundary (V1 (cursor 5 (just (episode 1 true))) 5) (true ∷ true ∷ true ∷ true ∷ true ∷ []) ((frame 5 true v1) ∷ (frame 4 true v2) ∷ (frame 3 true v1) ∷ (frame 2 true v1) ∷ (frame 1 true v1) ∷ []) ((event 1 2 v1) ∷ [])
return31 = refl
